
name: Kudos for Code
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  kudos:
    name: Semicolons Kudos
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LoremLabs/kudos-for-code-action@2ed632b3449f07f4b3d5a19f1c96cc71514904f8
        with:
          search-dir: "."
          destination: "artifact"
          generate-nomerges: true
          generate-validemails: true
          generate-limitdepth: 2
          generate-fromrepo: true
          analyze-repo: false

