
name: Kudos for Code
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  kudos:
    name: Semicolons Kudos
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LoremLabs/kudos-for-code-action@9567ce978b189abdf663a63368b7610ca0972cf8
        with:
          search-dir: "."
          destination: "artifact"
          generate-nomerges: true
          generate-validemails: true
          generate-limitdepth: 2
          generate-fromrepo: true
          analyze-repo: false
          
